<?php
declare(strict_types=1);
require_once __DIR__ . '/../config.php';
$user = currentUser();
if (!$user || $user['role'] !== 'admin') { header('Location: login.php'); exit; }
$csrfToken = csrfToken();
?><!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Kelola Produk | Admin</title><style>
:root{--green:#2f6b3f;--dark:#1f4d2e;--cream:#f8f6ed;--line:#dfe5dc}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:#1f2d22;font:14px Arial,sans-serif}header{background:var(--dark);color:#fff;padding:22px 5%;display:flex;justify-content:space-between;gap:20px;align-items:center}header h1{margin:0;font-size:22px}header a{color:#fff;text-decoration:none}main{width:min(1100px,92%);margin:28px auto}.panel,.product{background:#fff;border:1px solid var(--line);border-radius:10px;padding:18px;margin:14px 0}.form{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.form label{display:grid;gap:5px;font-weight:700}.form input,.form textarea{padding:10px;border:1px solid var(--line);border-radius:6px;font:inherit}.form textarea{min-height:78px;resize:vertical}.wide{grid-column:1/-1}button{padding:9px 13px;border:0;border-radius:6px;background:var(--green);color:#fff;font-weight:700;cursor:pointer}.danger{background:#9e3b31}.products{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px}.product img{width:75px;height:75px;object-fit:contain;float:right;background:#f5f3ea}.product h3{margin:0 0 7px;color:var(--dark)}.product p{margin:5px 0}.detail{color:#69736b;font-size:12px;line-height:1.5}.actions{display:flex;gap:8px;margin-top:12px}.message{color:#a33;min-height:20px}.modal-backdrop{position:fixed;inset:0;background:#17271c99;display:none;align-items:center;justify-content:center;padding:20px;z-index:20}.modal-backdrop.show{display:flex}.modal{width:min(760px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:12px;padding:22px}.modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.modal-head h2{margin:0;color:var(--dark)}.close{background:transparent;color:var(--dark);font-size:22px;padding:2px 8px}.image-preview{max-width:140px;max-height:100px;object-fit:contain;background:#f5f3ea;border-radius:6px}@media(max-width:650px){.form{grid-template-columns:1fr}.wide{grid-column:auto}}
</style></head><body><header><h1>Kelola Produk</h1><div><a href="index.php">Pembayaran</a> &middot; <a href="../index.php">Toko</a></div></header><main><section class="panel"><h2>Produk</h2><button id="addProduct" type="button">Tambah produk baru</button><p id="message" class="message"></p></section><h2>Daftar produk</h2><div id="products" class="products">Memuat...</div></main><div class="modal-backdrop" id="modalBackdrop"><section class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h2 id="modalTitle">Tambah produk</h2><button class="close" type="button" id="closeModal" aria-label="Tutup">&times;</button></div><form id="productForm" class="form"><input type="hidden" name="id"><label>Nama<input name="name" required maxlength="160"></label><label>ID slug<input name="slug" placeholder="otomatis dari nama" maxlength="80"></label><label>Harga<input name="price" type="number" min="0" required></label><label>Berat (gram)<input name="weight" type="number" min="1" required value="80"></label><label class="wide">Gambar<input name="image" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="wide"><img id="imagePreview" class="image-preview" alt="Pratinjau gambar" hidden></div><label>Kategori<input name="category" required maxlength="120" value="SNACK JAMUR ORGANIK"></label><label>Badge<input name="badge" maxlength="80" placeholder="BEST SELLER"></label><label>Klaim<input name="claim" maxlength="80" placeholder="TANPA TEPUNG"></label><label>Rating<input name="rating" type="number" min="0" max="5" step="0.1" value="0"></label><label>Jumlah terjual<input name="soldCount" type="number" min="0" value="0"></label><label class="wide">Deskripsi<textarea name="description" maxlength="5000"></textarea></label><label class="wide">Komposisi<textarea name="composition" maxlength="500"></textarea></label><label class="wide">Tambahan deskripsi 1<textarea name="highlightOneText" maxlength="180" placeholder="Misal: terbuat dari 100% jamur asli"></textarea></label><label class="wide">Tambahan deskripsi 2<textarea name="highlightTwoText" maxlength="180" placeholder="Misal: Digoreng hingga super renyah"></textarea></label><label><span>Aktif</span><input name="isActive" type="checkbox" checked></label><div class="wide"><button>Simpan produk</button></div></form></section></div><script>
const csrfToken=<?= json_encode($csrfToken) ?>,box=document.getElementById('products'),message=document.getElementById('message'),backdrop=document.getElementById('modalBackdrop'),form=document.getElementById('productForm'),preview=document.getElementById('imagePreview');let products=[];
function closeModal(){backdrop.classList.remove('show')}function openModal(product){form.reset();preview.hidden=true;form.elements.isActive.checked=true;document.getElementById('modalTitle').textContent=product?'Edit produk':'Tambah produk';if(product){form.elements.id.value=product.id;['name','price','category','badge','claim','rating','description','composition'].forEach(key=>form.elements[key].value=product[key]??'');form.elements.highlightOneText.value=product.highlight_one_text??'';form.elements.highlightTwoText.value=product.highlight_two_text??'';form.elements.weight.value=product.weight_gram;form.elements.slug.value=product.id;form.elements.isActive.checked=Number(product.is_active)===1;preview.src='../'+product.image;preview.hidden=false}backdrop.classList.add('show')}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}const money=value=>'Rp'+Number(value).toLocaleString('id-ID');
async function load(){const response=await fetch('../api/products.php');const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||'Produk gagal dimuat.');products=result.products;box.innerHTML=products.map(p=>`<article class="product"><img src="../${esc(p.image)}" alt=""><h3>${esc(p.name)}</h3><p>${money(p.price)} &middot; ${p.weight_gram} gram</p><p>${esc(p.category)} &middot; ${p.is_active==1?'Aktif':'Nonaktif'}</p><p class="detail">${esc(p.description||'Belum ada deskripsi.')}</p><div class="actions"><button data-edit="${esc(p.id)}">Edit</button><button class="danger" data-delete="${esc(p.id)}">Nonaktifkan</button></div></article>`).join('')}
document.getElementById('addProduct').onclick=()=>openModal();document.getElementById('closeModal').onclick=closeModal;backdrop.onclick=event=>{if(event.target===backdrop)closeModal()};form.elements.image.onchange=event=>{const file=event.target.files[0];if(file){preview.src=URL.createObjectURL(file);preview.hidden=false}};
form.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(form);data.append('action',form.elements.id.value?'update':'create');data.set('id',form.elements.id.value||form.elements.slug.value);data.set('isActive',form.elements.isActive.checked?'1':'0');try{const response=await fetch('../api/products.php',{method:'POST',headers:{'X-CSRF-Token':csrfToken},body:data});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message);closeModal();message.textContent='Produk berhasil disimpan.';load()}catch(error){message.textContent=error.message}});
box.addEventListener('click',async event=>{const edit=event.target.closest('[data-edit]');if(edit){openModal(products.find(product=>product.id===edit.dataset.edit));return}const remove=event.target.closest('[data-delete]');if(remove){if(!confirm('Nonaktifkan produk ini?'))return;const data=new FormData();data.append('action','delete');data.append('id',remove.dataset.delete);const response=await fetch('../api/products.php',{method:'POST',headers:{'X-CSRF-Token':csrfToken},body:data});const result=await response.json();if(!response.ok||!result.success)message.textContent=result.message;load()}});load().catch(error=>message.textContent=error.message);
</script><script>
['slug','rating','soldCount'].forEach(name=>{const input=form.elements[name];if(input?.closest('label'))input.closest('label').hidden=true;});
</script></body></html>
