<?php
declare(strict_types=1);
require_once __DIR__ . '/../config.php';
$user = currentUser();
if (!$user || $user['role'] !== 'customer') { header('Location: ../auth.php'); exit; }
$csrfToken = csrfToken();
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Dashboard Saya | Mushroom Organik</title><style>
:root{--green:#2f6b3f;--dark:#1f4d2e;--cream:#f8f6ed;--line:#dfe5dc}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:#1f2d22;font:14px Arial,sans-serif}header{background:var(--dark);color:#fff;padding:22px 5%;display:flex;justify-content:space-between;gap:20px;align-items:center}header h1{margin:0;font-size:22px}header a,header button{color:#fff;background:transparent;border:0;text-decoration:none;cursor:pointer;font:inherit}main{width:min(1000px,92%);margin:28px auto}.summary{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:18px}.summary div{background:#fff;border:1px solid var(--line);border-radius:8px;padding:12px 16px}.summary strong{display:block;font-size:20px;color:var(--dark)}.summary span{color:#69736b;font-size:12px}.order{background:#fff;border:1px solid var(--line);border-radius:10px;margin:14px 0;padding:18px}.order-head{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.order h3{margin:0;color:var(--dark)}.status{display:inline-block;padding:7px 10px;border-radius:6px;background:#edf4e9;color:var(--green);font-weight:700}.meta{color:#69736b;font-size:13px}.items{width:100%;border-collapse:collapse;margin-top:14px}.items td{border-top:1px solid var(--line);padding:8px 0}.total{text-align:right;font-weight:700;color:var(--dark)}.proof{color:var(--green)}.empty{background:#fff;padding:32px;text-align:center;border:1px solid var(--line);border-radius:10px}.message{color:#a33}
</style></head><body><header><h1>Pesanan Saya</h1><div><?= htmlspecialchars($user['name'], ENT_QUOTES, 'UTF-8') ?> &middot; <a href="../index.php">Belanja lagi</a> &middot; <button id="logout">Keluar</button></div></header><main><p id="message" class="message"></p><div id="orders">Memuat pesanan...</div></main><script>
const csrfToken=<?= json_encode($csrfToken) ?>,box=document.getElementById('orders'),message=document.getElementById('message');const money=value=>'Rp'+Number(value).toLocaleString('id-ID');const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){try{const response=await fetch('../api/user.php');const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||'Pesanan gagal dimuat.');if(!result.orders.length){box.innerHTML='<div class="empty">Belum ada pesanan. <a href="../index.php">Mulai belanja</a>.</div>';return;}box.innerHTML=result.orders.map(order=>`<article class="order"><div class="order-head"><div><h3>${esc(order.id)}</h3><div class="meta">${esc(order.created_at)} &middot; ${esc(order.city)}, ${esc(order.province)}</div></div><div class="status">Pembayaran: ${esc(order.payment_status)}<br>Pesanan: ${esc(order.order_status)}</div></div><table class="items">${order.items.map(item=>`<tr><td>${esc(item.product_name)} x ${item.quantity}</td><td>${money(item.line_total)}</td></tr>`).join('')}</table><p class="total">Total: ${money(order.total)}</p>${order.admin_note?`<div class="meta">Catatan admin: ${esc(order.admin_note)}</div>`:''}</article>`).join('');}catch(error){message.textContent=error.message;}}document.getElementById('logout').addEventListener('click',async()=>{await fetch('../api/auth.php?action=logout',{method:'POST',headers:{'X-CSRF-Token':csrfToken}});location.href='../auth.php';});load();
</script></body></html>
